-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.AuthenticateUserResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.AuthenticateUserResult
selection constructor =
    Object.selection constructor
token : Field String Api.Object.AuthenticateUserResult
token =
      Object.fieldDecoder "token" [] (Decode.string)


user : SelectionSet decodesTo Api.Object.User -> Field decodesTo Api.Object.AuthenticateUserResult
user object_ =
      Object.selectionField "user" [] (object_) (identity)
