-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Board exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Board
selection constructor =
    Object.selection constructor
columns : SelectionSet decodesTo Api.Object.Column -> Field (Maybe (List (Maybe decodesTo))) Api.Object.Board
columns object_ =
      Object.selectionField "columns" [] (object_) (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


hashid : Field (Maybe String) Api.Object.Board
hashid =
      Object.fieldDecoder "hashid" [] (Decode.string |> Decode.nullable)


id : Field (Maybe Api.Scalar.Id) Api.Object.Board
id =
      Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Id |> Decode.nullable)


name : Field (Maybe String) Api.Object.Board
name =
      Object.fieldDecoder "name" [] (Decode.string |> Decode.nullable)
