-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Card exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Card
selection constructor =
    Object.selection constructor
columnId : Field (Maybe Api.Scalar.Id) Api.Object.Card
columnId =
      Object.fieldDecoder "columnId" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Id |> Decode.nullable)


id : Field (Maybe Api.Scalar.Id) Api.Object.Card
id =
      Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Id |> Decode.nullable)


position : Field (Maybe Float) Api.Object.Card
position =
      Object.fieldDecoder "position" [] (Decode.float |> Decode.nullable)


title : Field (Maybe String) Api.Object.Card
title =
      Object.fieldDecoder "title" [] (Decode.string |> Decode.nullable)
