-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.ColumnEvent exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.ColumnEvent
selection constructor =
    Object.selection constructor
action : Field (Maybe String) Api.Object.ColumnEvent
action =
      Object.fieldDecoder "action" [] (Decode.string |> Decode.nullable)


column : SelectionSet decodesTo Api.Object.Column -> Field (Maybe decodesTo) Api.Object.ColumnEvent
column object_ =
      Object.selectionField "column" [] (object_) (identity >> Decode.nullable)
