-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Column exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Column
selection constructor =
    Object.selection constructor
cards : SelectionSet decodesTo Api.Object.Card -> Field (Maybe (List (Maybe decodesTo))) Api.Object.Column
cards object_ =
      Object.selectionField "cards" [] (object_) (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


id : Field (Maybe Api.Scalar.Id) Api.Object.Column
id =
      Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Id |> Decode.nullable)


name : Field (Maybe String) Api.Object.Column
name =
      Object.fieldDecoder "name" [] (Decode.string |> Decode.nullable)


position : Field (Maybe Int) Api.Object.Column
position =
      Object.fieldDecoder "position" [] (Decode.int |> Decode.nullable)
