-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object exposing (..)


type AuthenticateUserResult
    = AuthenticateUserResult


type Board
    = Board


type Card
    = Card


type Column
    = Column


type ColumnEvent
    = ColumnEvent


type CreateBoardResult
    = CreateBoardResult


type CreateCardResult
    = CreateCardResult


type CreateColumnResult
    = CreateColumnResult


type InputError
    = InputError


type RegisterUserResult
    = RegisterUserResult


type UpdateColumnResult
    = UpdateColumnResult


type User
    = User
