-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Subscription exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Graphql.Internal.Builder.Object as Object
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Json.Decode as Decode exposing (Decoder)
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a top-level mutation. The request can be sent with
functions from `Graphql.Http`.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) RootSubscription
selection constructor =
    Object.selection constructor
type alias BoardRequiredArguments = { hashid : String }

board : BoardRequiredArguments -> SelectionSet decodesTo Api.Object.Board -> Field (Maybe decodesTo) RootSubscription
board requiredArgs object_ =
      Object.selectionField "board" [ Argument.required "hashid" requiredArgs.hashid (Encode.string) ] (object_) (identity >> Decode.nullable)


type alias BoardColumnEventRequiredArguments = { boardHashid : String }

boardColumnEvent : BoardColumnEventRequiredArguments -> SelectionSet decodesTo Api.Object.ColumnEvent -> Field (Maybe decodesTo) RootSubscription
boardColumnEvent requiredArgs object_ =
      Object.selectionField "boardColumnEvent" [ Argument.required "boardHashid" requiredArgs.boardHashid (Encode.string) ] (object_) (identity >> Decode.nullable)
